function [flength,fangle]= com_flength_fangle_ling(meshpoint,length_c,raw,slice)


%Initialization
flength(1:slice,1:raw,1:3)=0;
fangle(1:slice,1:raw,1:3)=0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Search neighboring points on the 1st row and calculate f
i=1;
n=2; %number of neighboring points
  for j=1:4:raw-3
      neighbor2=meshpoint(i+2,j+2,:);
      if j==1
         neighbor1=meshpoint(i+2,raw-1,:);        
      else
         neighbor1=meshpoint(i+2,j-2,:);
      end  
  % Distance between the point and neighboring point 1   
      dneighbor1=sqrt((meshpoint(i,j,1)-neighbor1(1))* (meshpoint(i,j,1)-...
                  neighbor1(1))+(meshpoint(i,j,2)-neighbor1(2))*...
                  (meshpoint(i,j,2)-neighbor1(2))+(meshpoint(i,j,3)-...
                  neighbor1(3))*(meshpoint(i,j,3)-neighbor1(3)));
      % Distance between the point and neighboring point 2         
      dneighbor2=sqrt((meshpoint(i,j,1)-neighbor2(1))* (meshpoint(i,j,1)-...
                  neighbor2(1))+(meshpoint(i,j,2)-neighbor2(2))*...
                  (meshpoint(i,j,2)-neighbor2(2))+(meshpoint(i,j,3)-...
                  neighbor2(3))*(meshpoint(i,j,3)-neighbor2(3))); 

      % Calculate flength
      flength(i,j,:)=((length_c-dneighbor1)*(meshpoint(i,j,:)-neighbor1)/dneighbor1+...
         (length_c-dneighbor2)*(meshpoint(i,j,:)-neighbor2)/dneighbor2)/n;

      pangle12=(neighbor1+neighbor2)/2;
      dpangle12=sqrt((meshpoint(i,j,1)-pangle12(1))* (meshpoint(i,j,1)-...
                  pangle12(1))+(meshpoint(i,j,2)-pangle12(2))*...
                  (meshpoint(i,j,2)-pangle12(2))+(meshpoint(i,j,3)-...
                  pangle12(3))*(meshpoint(i,j,3)-pangle12(3)));
     angle12=2*acos(dpangle12/dneighbor1);

     % Calculate fangle
     fangle(i,j,:)=-abs(dneighbor1*cos(angle12))*(meshpoint(i,j,:)-pangle12)/dpangle12;
  end 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Search neighboring points on the last row and calculate f
i=slice;
n=2; % Number of neighboring points 
  for j=1:4:raw-3
      neighbor2=meshpoint(i-2,j+2,:);
      if j==1
         neighbor1=meshpoint(i-2,raw-1,:);        
      else
         neighbor1=meshpoint(i-2,j-2,:);
      end  
 % Distance between the point and neighboring point 1    
     dneighbor1=sqrt((meshpoint(i,j,1)-neighbor1(1))* (meshpoint(i,j,1)-...
                  neighbor1(1))+(meshpoint(i,j,2)-neighbor1(2))*...
                  (meshpoint(i,j,2)-neighbor1(2))+(meshpoint(i,j,3)-...
                  neighbor1(3))*(meshpoint(i,j,3)-neighbor1(3)));
     % Distance between the point and neighboring point 2       
     dneighbor2=sqrt((meshpoint(i,j,1)-neighbor2(1))* (meshpoint(i,j,1)-...
                  neighbor2(1))+(meshpoint(i,j,2)-neighbor2(2))*...
                  (meshpoint(i,j,2)-neighbor2(2))+(meshpoint(i,j,3)-...
                  neighbor2(3))*(meshpoint(i,j,3)-neighbor2(3))); 

      % Calculate fangle 
      flength(i,j,:)=((length_c-dneighbor1)*(meshpoint(i,j,:)-neighbor1)/dneighbor1+...
         (length_c-dneighbor2)*(meshpoint(i,j,:)-neighbor2)/dneighbor2)/n;


      pangle12=(neighbor1+neighbor2)/2;
      dpangle12=sqrt((meshpoint(i,j,1)-pangle12(1))* (meshpoint(i,j,1)-...
                  pangle12(1))+(meshpoint(i,j,2)-pangle12(2))*...
                  (meshpoint(i,j,2)-pangle12(2))+(meshpoint(i,j,3)-...
                  pangle12(3))*(meshpoint(i,j,3)-pangle12(3)));
      angle12=2*acos(dpangle12/dneighbor1);

      % Calculate fangle (º∆À„fangle)
      fangle(i,j,:)=-abs(dneighbor1*cos(angle12))*(meshpoint(i,j,:)-pangle12)/dpangle12;
  end      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Search neighboring points on the 3rd, 7th, 11th, ..., (slice-2)th row and calculate f 
% 
n=4;
for i=3:4:slice-2
   for j=3:4:raw-1
     if j==raw-1
              neighbor2=meshpoint(i-2,1,:);
              neighbor4=meshpoint(i+2,1,:);
     else
             neighbor2=meshpoint(i-2,j+2,:);
             neighbor4=meshpoint(i+2,j+2,:);
     end
     neighbor1=meshpoint(i-2,j-2,:);
     neighbor3=meshpoint(i+2,j-2,:);
        
     % Distance between the point and neighboring point 1 
     dneighbor1=sqrt((meshpoint(i,j,1)-neighbor1(1))* (meshpoint(i,j,1)-...
              neighbor1(1))+(meshpoint(i,j,2)-neighbor1(2))*...
              (meshpoint(i,j,2)-neighbor1(2))+(meshpoint(i,j,3)-...
              neighbor1(3))*(meshpoint(i,j,3)-neighbor1(3)));
     % Distance between the point and neighboring point 2    
     dneighbor2=sqrt((meshpoint(i,j,1)-neighbor2(1))* (meshpoint(i,j,1)-...
              neighbor2(1))+(meshpoint(i,j,2)-neighbor2(2))*...
              (meshpoint(i,j,2)-neighbor2(2))+(meshpoint(i,j,3)-...
              neighbor2(3))*(meshpoint(i,j,3)-neighbor2(3)));
     % Distance between the point and neighboring point 3 
     dneighbor3=sqrt((meshpoint(i,j,1)-neighbor3(1))* (meshpoint(i,j,1)-...
              neighbor3(1))+(meshpoint(i,j,2)-neighbor3(2))*...
              (meshpoint(i,j,2)-neighbor3(2))+(meshpoint(i,j,3)-...
              neighbor3(3))*(meshpoint(i,j,3)-neighbor3(3)));
     % Distance between the point and neighboring point 4  
     dneighbor4=sqrt((meshpoint(i,j,1)-neighbor4(1))* (meshpoint(i,j,1)-...
              neighbor4(1))+(meshpoint(i,j,2)-neighbor4(2))*...
              (meshpoint(i,j,2)-neighbor4(2))+(meshpoint(i,j,3)-...
              neighbor4(3))*(meshpoint(i,j,3)-neighbor4(3)));  
          
     % Calculate flength 
     flength(i,j,:)=((length_c-dneighbor1)*(meshpoint(i,j,:)-neighbor1)/dneighbor1+...
     (length_c-dneighbor2)*(meshpoint(i,j,:)-neighbor2)/dneighbor2+...
     (length_c-dneighbor3)*(meshpoint(i,j,:)-neighbor3)/dneighbor3+...
     (length_c-dneighbor4)*(meshpoint(i,j,:)-neighbor4)/dneighbor4)/n;
 
    
     
     pangle12=(neighbor1+neighbor2)/2;
     pangle13=(neighbor1+neighbor3)/2;
     pangle24=(neighbor2+neighbor4)/2;
     pangle34=(neighbor3+neighbor4)/2;
     
     dpangle12=sqrt((meshpoint(i,j,1)-pangle12(1))* (meshpoint(i,j,1)-...
              pangle12(1))+(meshpoint(i,j,2)-pangle12(2))*...
              (meshpoint(i,j,2)-pangle12(2))+(meshpoint(i,j,3)-...
              pangle12(3))*(meshpoint(i,j,3)-pangle12(3)));
     dpangle13=sqrt((meshpoint(i,j,1)-pangle13(1))* (meshpoint(i,j,1)-...
              pangle13(1))+(meshpoint(i,j,2)-pangle13(2))*...
              (meshpoint(i,j,2)-pangle13(2))+(meshpoint(i,j,3)-...
              pangle13(3))*(meshpoint(i,j,3)-pangle13(3)));    
     dpangle24=sqrt((meshpoint(i,j,1)-pangle24(1))* (meshpoint(i,j,1)-...
              pangle24(1))+(meshpoint(i,j,2)-pangle24(2))*...
              (meshpoint(i,j,2)-pangle24(2))+(meshpoint(i,j,3)-...
              pangle24(3))*(meshpoint(i,j,3)-pangle24(3)));
    dpangle34=sqrt((meshpoint(i,j,1)-pangle34(1))* (meshpoint(i,j,1)-...
              pangle34(1))+(meshpoint(i,j,2)-pangle34(2))*...
              (meshpoint(i,j,2)-pangle34(2))+(meshpoint(i,j,3)-...
              pangle34(3))*(meshpoint(i,j,3)-pangle34(3)));
          
    angle12=2*acos(dpangle12/dneighbor1);
    angle13=2*acos(dpangle12/dneighbor1);
    angle24=2*acos(dpangle12/dneighbor2);
    angle34=2*acos(dpangle12/dneighbor3);
    
    % Calculate fangle 
    fangle(i,j,:)=-(abs(dneighbor1*cos(angle12))*(meshpoint(i,j,:)-pangle12)/...
     dpangle12+abs(dneighbor1*cos(angle13))*(meshpoint(i,j,:)-pangle13)/...
     dpangle13+abs(dneighbor2*cos(angle24))*(meshpoint(i,j,:)-pangle24)/...
     dpangle24-abs(dneighbor3*cos(angle34))*(meshpoint(i,j,:)-pangle34)/...
        dpangle34)/n;
   end
end
      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Search neighboring points on the 5th, 9th, 13th, ..., (slice-4)th row and calculate f 
% 
n=4;
for i=5:4:slice-4
   for j=1:4:raw-3
     if j==1
              neighbor1=meshpoint(i-2,raw-1,:);
              neighbor3=meshpoint(i+2,raw-1,:);
     else
             neighbor1=meshpoint(i-2,j-2,:);
             neighbor3=meshpoint(i+2,j-2,:);
     end
     neighbor2=meshpoint(i-2,j+2,:);
     neighbor4=meshpoint(i+2,j+2,:);
        
     % Distance between the point and neighboring point 1    
     dneighbor1=sqrt((meshpoint(i,j,1)-neighbor1(1))* (meshpoint(i,j,1)-...
              neighbor1(1))+(meshpoint(i,j,2)-neighbor1(2))*...
              (meshpoint(i,j,2)-neighbor1(2))+(meshpoint(i,j,3)-...
              neighbor1(3))*(meshpoint(i,j,3)-neighbor1(3)));
     % Distance between the point and neighboring point 2          
     dneighbor2=sqrt((meshpoint(i,j,1)-neighbor2(1))* (meshpoint(i,j,1)-...
              neighbor2(1))+(meshpoint(i,j,2)-neighbor2(2))*...
              (meshpoint(i,j,2)-neighbor2(2))+(meshpoint(i,j,3)-...
              neighbor2(3))*(meshpoint(i,j,3)-neighbor2(3)));
     % Distance between the point and neighboring point 3  
    dneighbor3=sqrt((meshpoint(i,j,1)-neighbor3(1))* (meshpoint(i,j,1)-...
              neighbor3(1))+(meshpoint(i,j,2)-neighbor3(2))*...
              (meshpoint(i,j,2)-neighbor3(2))+(meshpoint(i,j,3)-...
              neighbor3(3))*(meshpoint(i,j,3)-neighbor3(3)));
     % Distance between the point and neighboring point 4         
     dneighbor4=sqrt((meshpoint(i,j,1)-neighbor4(1))* (meshpoint(i,j,1)-...
              neighbor4(1))+(meshpoint(i,j,2)-neighbor4(2))*...
              (meshpoint(i,j,2)-neighbor4(2))+(meshpoint(i,j,3)-...
              neighbor4(3))*(meshpoint(i,j,3)-neighbor4(3)));  
          
     % Calculate flength 
     flength(i,j,:)=((length_c-dneighbor1)*(meshpoint(i,j,:)-neighbor1)/dneighbor1+...
     (length_c-dneighbor2)*(meshpoint(i,j,:)-neighbor2)/dneighbor2+...
     (length_c-dneighbor3)*(meshpoint(i,j,:)-neighbor3)/dneighbor3+...
     (length_c-dneighbor4)*(meshpoint(i,j,:)-neighbor4)/dneighbor4)/n;
 
         
     pangle12=(neighbor1+neighbor2)/2;
     pangle13=(neighbor1+neighbor3)/2;
     pangle24=(neighbor2+neighbor4)/2;
     pangle34=(neighbor3+neighbor4)/2;
     
     dpangle12=sqrt((meshpoint(i,j,1)-pangle12(1))* (meshpoint(i,j,1)-...
              pangle12(1))+(meshpoint(i,j,2)-pangle12(2))*...
              (meshpoint(i,j,2)-pangle12(2))+(meshpoint(i,j,3)-...
              pangle12(3))*(meshpoint(i,j,3)-pangle12(3)));
     dpangle13=sqrt((meshpoint(i,j,1)-pangle13(1))* (meshpoint(i,j,1)-...
              pangle13(1))+(meshpoint(i,j,2)-pangle13(2))*...
              (meshpoint(i,j,2)-pangle13(2))+(meshpoint(i,j,3)-...
              pangle13(3))*(meshpoint(i,j,3)-pangle13(3)));    
     dpangle24=sqrt((meshpoint(i,j,1)-pangle24(1))* (meshpoint(i,j,1)-...
              pangle24(1))+(meshpoint(i,j,2)-pangle24(2))*...
              (meshpoint(i,j,2)-pangle24(2))+(meshpoint(i,j,3)-...
              pangle24(3))*(meshpoint(i,j,3)-pangle24(3)));
    dpangle34=sqrt((meshpoint(i,j,1)-pangle34(1))* (meshpoint(i,j,1)-...
              pangle34(1))+(meshpoint(i,j,2)-pangle34(2))*...
              (meshpoint(i,j,2)-pangle34(2))+(meshpoint(i,j,3)-...
              pangle34(3))*(meshpoint(i,j,3)-pangle34(3)));
          
    angle12=2*acos(dpangle12/dneighbor1);
    angle13=2*acos(dpangle12/dneighbor1);
    angle24=2*acos(dpangle12/dneighbor2);
    angle34=2*acos(dpangle12/dneighbor3);
    
    % Calculate fangle 
    fangle(i,j,:)=-(abs(dneighbor1*cos(angle12))*(meshpoint(i,j,:)-pangle12)/...
     dpangle12+abs(dneighbor1*cos(angle13))*(meshpoint(i,j,:)-pangle13)/...
     dpangle13+abs(dneighbor2*cos(angle24))*(meshpoint(i,j,:)-pangle24)/...
     dpangle24-abs(dneighbor3*cos(angle34))*(meshpoint(i,j,:)-pangle34)/...
        dpangle34)/n;
   end
end      